<?php
// $Id: xmpp_api.install,v

/**
 * Implementation of hook_enable().
 */
function xmpp_api_enable() {
  drupal_set_message(t('XMPP API module successfully installed. Please review the <a href="@settings">configuration settings</a>.', array('@settings' => url('admin/xmppframework/xmpp_api'))));
}

/**
 * Implementation of hook_install().
 */
function xmpp_api_install() {
}

/**
 * Implementation of hook_uninstall().
 */
function xmpp_api_uninstall() {
}

